[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[tools]
eza = "0.23.4"
fd = "10.3.0"
fzf = "0.66.1"
neovim = "0.11.4"
python = "3.14.0"
ripgrep = "15.1.0"
rust = "1.91.0"
tmux = "3.5a"
uv = "0.9.7"
go = "1.25.3"

